FROM node:24-alpine AS base

ENV PNPM_HOME=/usr/local/bin
ENV NODE_ENV=development

# Build stage
FROM base AS development
WORKDIR /app

RUN apk add --no-cache --virtual .gyp python3 make g++
RUN corepack enable && corepack prepare pnpm@latest --activate

COPY package*.json ./
COPY pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile || npm install

COPY . .

RUN pnpm prune || npm prune

CMD ["sh", "-c", "npx prisma generate && npm run start:dev"]

EXPOSE 8000
